### ISSUE TITLE
Initialize admin with specific roles[FR]

### ISSUE THREAD

**Issue by raghuchahar007** [firebase/firebase-admin-node#1033]
I want to initialize the firebase app without a service account i.e I wants to use it for cloud messaging only which needs only web API key, there should be a option to initialize firebase app with specific roles/permissions. 
for ex: One should be able to initialize firebase admin with web app key also with limited permissions like firebase messaging.

If this already exists there are no docs referring to this.

**Comment by hiranya911** [comment]
Admin SDK uses OAuth2 for authorizing requests, and therefore the service account is required. We also don't wish to support web API keys for FCM, since they are not a very secure way for sending notifications. Service accounts have roles and permissions tied to them (configured via IAM), which is the recommended way to control what roles the SDK should have.
