### ISSUE TITLE
[FR] change the export in index 

### ISSUE THREAD

**Issue by yedri101** [firebase/firebase-admin-node#1086]
the problem :
for avoiding use esModuleInterop - in typescript when import 

**solution I'd like**
change to export = {firebase}

thanks

**Comment by hiranya911** [comment]
You can use the following import styles without module interop: 

1. `import * as admin from 'firebase-admin'`
2. `import admin = require('firebase-admin')`

Only the default import style (`import admin from 'firebase-admin'`) requires module interop, but that's to be expected.

We do not want to change the existing export, since that is likely to be a breaking change for many developers. We specifically don't want to do `export = {firebase}`, as that would export an object with the key `firebase`, which is not something we want to support.
