### ISSUE TITLE
TypeError: instance.INTERNAL.registerComponent is not a function     at registerDatabase

### ISSUE THREAD

**Issue by Stas-Buzunko** [firebase/firebase-admin-node#1114]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: mojave
  * Firebase SDK version: ^9.4.2
  * Firebase Product: firebase-admin
  * Node.js version: v10.16.0
  * NPM version: 6.9.0

#### Steps to reproduce:

exports.test = functions.https.onRequest((req, res) => {
  res.sendStatus(200)

  admin.database().ref('WeeklySchedule')
  .once('value')
  .then(s => console.log(s.val()))
})

**Comment by Stas-Buzunko** [comment]
after updating firebase-js-sdk in parent folder it started working. why does firebase-admin/functions even check anything in parent folder's node_modules? wtf?

**Comment by hiranya911** [comment]
You haven't provided any details on how you installed/updated the Admin SDK. Typically, all its dependencies will be installed into a `node_modules` directory at the same level. But for some reason that hasn't happened in this case (my guess is due to an old package lock file in your project). When a dependency is not found in the `node_modules` directory, Node.js automatically starts looking at other `node_modules` directories at parent levels:

https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-nodejs-resolves-modules

**Comment by hiranya911** [comment]
I think this is the problematic bit of code: https://github.com/firebase/firebase-js-sdk/blob/44b5251d0527d1aa768959765ff04093a04dd8ab/packages/database/index.node.ts#L124-L139

The `registerDatabase()` method shouldn't be called when using the Admin SDK, because `@firebase/app` is not meant to be installed alongside `firebase-admin`. But you seem to have this package installed somewhere in your project hierarchy, where it's visible to the Node runtime, and furthermore it was an older version that didn't provide the `registerComponent()` method.  Whenever you have `@firebase/app` anywhere near `firebase-admin` you need to make sure it's compatible with the version of `@firebase/database` that Admin SDK is using. You seemed to have fixed it for your project by installing the latest JS SDK at the parent level. 

There's no simple fix for this problem at our end unfortunately. It requires rethinking and reorganizing how we consume the `@firebase/database` dependency. There's an early stage proposal from the JS SDK team to ship a standalone RTDB package with no dependencies on `@firebase/app`. That might provide a more robust solution to problems like this.
