### ISSUE TITLE
Cannot use firebase-admin firestore emulator in Jest with jsdom test environment

### ISSUE THREAD

**Issue by Mattinton** [firebase/firebase-admin-node#1135]
### [REQUIRED] Environment info

**firebase-tools:** 9.2.0

**Platform:** macOS

### [REQUIRED] Test case

I have the following code snippet running in setupTests.ts in a create-react-app project

```ts
import firebaseAdmin from 'firebase-admin';  

beforeEach(async () => {
  const app = firebaseAdmin.initializeApp({ projectId: "[TEST_ID]" });
  const test = await app.firestore().collection('test').get();
});
```

### [REQUIRED] Steps to reproduce

With `firebase emulators:start` run `npm run test`

### [REQUIRED] Expected behavior

Retrieve the contents of the test collection 

### [REQUIRED] Actual behavior

```
{"servicePath":"localhost","port":8080,"clientConfig":{},"fallback":true,"sslCreds":{"callCredentials":{}},"projectId":"[TEST_ID]","firebaseVersion":"9.4.2","libName":"gccl","libVersion":"4.8.1 fire/9.4.2","ssl":false,"customHeaders":{"Authorization":"Bearer owner"},"scopes":["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/datastore"]}You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client from google-auth-library.
```

When using --env=node the tests succeed but using the default --env=jsdom the tests fail with the above error.

Any help is appreciated. 
Thanks

**Comment by samtstern** [comment]
@Mattinton I've moved this over to the Admin Node repo as I don't think this is something we can address in the CLI. Maybe someone on the Firestore team will have an idea of why the Firestore Admin SDK is unhappy in a JSDOM environment!

**Comment by hiranya911** [comment]
Pretty sure `@google-cloud/firestore` won't work within any browser or browser-like environment. @schmidt-sebastian can you confirm?

**Comment by schmidt-sebastian** [comment]
`@google-cloud/firestore` uses GRPC, which is not yet compatible with browsers.

**Comment by amiller-gh** [comment]
fwiw, here is the culprit: https://github.com/googleapis/gax-nodejs/blob/055387b1f497f6a4132f228d82d95d9a6f6c53f7/src/fallback.ts#L132

And the corresponding `isBrowser` function: https://github.com/googleapis/gax-nodejs/blob/055387b1f497f6a4132f228d82d95d9a6f6c53f7/src/isbrowser.ts#L17

@schmidt-sebastian, using https://www.npmjs.com/package/jsdom is a fairly common pattern for frontend testing in many parts of the community. It provides a sub-set of browser APIs so you can run and test simple frontend code in Node.js.

When run with test runners like Jest, `window` is often injected as a global so the test files run in a browser-ish environment. If test writers want to do any firestore setup before running their frontend code, the firestore-admin package will run in a Node.js world where globals.window is actually defined!

That is despite the authors of jsdom explicitly warning against this!...

> We strongly advise against trying to "execute scripts" by mashing together the jsdom and Node global environments (e.g. by doing global.window = dom.window)

`google-gax` could use a scalpel instead of a sledge hammer – instead of simply checking for the existence of `window` to determine the environment, it could more selectively test for exactly what makes it incompatible with browser environments.

However, because polluting the global object is like... the *original sin* of programming, I feel like it should be on the people committing the offense to work around it :) 

Easiest way I've found is to simply take `window` out of the equation when running firestore setup calls:

```js
describe('Demo Test', () => {
  it('Runs firestore bootstrap code', async() => {
    delete global.window;
    await app.firestore().doc(`path/to/thing`).set({ foo: 'bar' }, { merge: true });
    global.window = tmp;
    runBrowserCodeNow();
  });
});
```

Other options include custom test runner environments to bootstrap jsdom without polluting the global scope, or simply testing with puppeteer in proper browser!

Hopefully this comment can help provide some context to anyone who find this in the future :)

**Comment by schmidt-sebastian** [comment]
I filed https://github.com/googleapis/gax-nodejs/issues/1046. We might be able to work around this even if `google-gax` is not to blame for this :)
