### ISSUE TITLE
Client SDK and Admin SDK return different timeStamp objects.

### ISSUE THREAD

**Issue by jakobnoergaard** [firebase/firebase-admin-node#1404]
Hi, I really hope you can help with an answer on this.

[REQUIRED] Step 2: Describe your environment

  "firebase-admin": "^9.11.0",
   "firebase-functions": "^3.14.1"

  * Firebase Product: Firestore Admin SDK
  * Node.js version: 14

[REQUIRED] Step 3: Describe the problem

The Admin SDK returns a different timestamp than the client SDK. This makes it unnecessarily complex to fetch data from both. Is there a specific reason for this? 

#### Steps to reproduce:

Create a timeStamp field in any firestore document and fetch the document with the client SDK and with a cloud function (Admin SDK). When comparing both docs you will see:

1. The client SDK returns a timeStamp as described in the docs and the prototype has toDate() etc. The naming of the timeStamp is { seconds: value, nanoSeconds: value }
2. The function (Admin SDK) returns a different timeStamp. It does not have the same prototype - it has none of the functions from the docs - toDate() etc.. - and the naming of the timeStamp is different. The naming here is { _seconds: value, _nanoSeconds: value }. Notice the _ before both keys.

Is there any specific reason for this and is it possible to get the correct timestamp, just like we get from the client SDK? 

I've tested this using the functions emulator:  "firebase-functions-test": "^0.3.1" 

#### Relevant Code:
It should be fairly easy to reproduce.

Kind regards,
Jakob

**Comment by hiranya911** [comment]
It is a different type but it certainly has a `toDate()` method and the usual `seconds` and `nanoseconds` properties: https://googleapis.dev/nodejs/firestore/latest/Timestamp.html

Here's some output from the Node.js REPL:

```
> const admin = require('firebase-admin')
undefined
> const ts = admin.firestore.Timestamp.now()
undefined
> ts.seconds
1628614245
> ts.nanoseconds
984000000
> ts.toDate()
2021-08-10T16:50:45.984Z
```

**Comment by jakobnoergaard** [comment]
Hi, hiranya911. 

I understand that. I am referring to situations where you return data from the cloud function. 

1. Use the Admin SDK to fetch a document from Firestore (a document with a timestamp).
2. Get document.data() in the cloud function and then return the data to the client.
3. The timeStamp on the document no longer has toDate() when received on the client. 

- Jakob

**Comment by hiranya911** [comment]
That depends on how you have chosen to pass data back from the function to your client. Assuming this transfer takes place over HTTPS+JSON, you might want to serialize the `Timestamp` in the server to a format the client can easily decode. In most JS applications you might want to use the UTC string format of the date for this purpose.

**Comment by joelmeaders** [comment]
@hiranya911 I have a monorepo with a shared library which includes various type interfaces, typed functions etc... I also have multiple clients and a functions project in this monorepo. I cannot compile my functions project because toJson is missing in the admin SDK. I do not want to add the admin SDK to all of my other projects.

I see this as a bug.

**Comment by chargome** [comment]
@joelmeaders just encountered the same issue, were you able to solve it?

**Comment by benneic** [comment]
@hiranya911  I agree with the sentiment on this issue. I am using NextJS which allows both server side static and client side dynamic rendering of pages using the same React components. 

In my case I have pages where I statically render each page at build time meaning I need to use the Admin SDK to access Firestore for data... then when a user has loaded the static page I use the Client SDK to create a snapshot to the same underlying data.

However because the fields with Timestamp objects have differing signatures I am forced to write boiler plate to handle the differences between the two SDKs.

A solution to this would be to use the same types definition (shape) to these objects as @joelmeaders has highlighted.

**Comment by benneic** [comment]
Alternatively is there a way to configure both of these SDKs to return javascript Date objects instead? That would save a world of effort for this use case.

**Comment by rcb4t2** [comment]
Hi @hiranya911 any updates on this?

Firestore Client SDK and Admin SDK should use the same definition for Timestamp

Working in monorepos or other situations with shared Typescript interfaces is complicated because `toJSON` method is missing on the Admin SDK definition

**Comment by Padreco-lbr** [comment]
Agreeing with @rcb4t2 about the complications in using typescript and monorepos, things get quite messy. But since I have no idea how hard it is to have a shared definition between Client and Admin SDKs for firebase team, I am currently unifying both Timestamps (Client and Admin) with:

```typescript
import { Timestamp } from "firebase/firestore";

export type TimestampClientAdmin = Omit<Timestamp, "toJSON">;
```

This is far from optimal, but a bearable workaround.

**Comment by chrysb** [comment]
FWIW, I've written a function that just converts all Timestamps within object to Dates after reading from the database.

I wish Firestore's javascript SDK would just return `Date` instead of `Timestamp` type. We don't need your type, Google.

For admin, just change `instanceof Timestamp` to `instanceof admin.firestore.Timestamp`

```
export const convertTimestampsToDates = (obj: any): any => {
  if (!obj) return obj

  if (obj instanceof Timestamp) {
    return obj.toDate()
  }
  if (Array.isArray(obj)) {
    return obj.map(convertTimestampsToDates)
  }
  if (typeof obj === 'object') {
    Object.keys(obj).forEach((key) => {
      obj[key] = convertTimestampsToDates(obj[key])
    })
  }
  return obj
}
```

**Comment by BenJackGill** [comment]
I have a monorepo and I wanted one type for both read/write and to use on admin/client.

So I create union types for admin and client Firestore versions, and then create a generic type that can be used for read and write operations.

```TypeScript
export type TimestampField<IsWrite extends boolean = false> =
  IsWrite extends true ? TimestampWrite : TimestampRead;

export type TimestampRead = AdminTimestamp | Timestamp;

export type TimestampWrite = AdminFieldValue | FieldValue;
```

Example when defining a doc type:
```TypeScript
export type MyDocument<IsWrite extends boolean = false> = {
  createdAt: TimestampField<IsWrite>;
};
```

Example when using as write operation:
```TypeScript
const myDocument: MyDocument<true> = {
   createdAt: FieldValue.serverTimestamp(),
 };
```

Example when using as read operation:
```TypeScript
myDocument.createdAt.toDate() // Returns a JavaScript Date object from the Timestamp
```

If anyone has a better idea let me know!
