### ISSUE TITLE
FR: Ability to link accounts via admin SDK

### ISSUE THREAD

**Issue by blackxored** [firebase/firebase-admin-node#155]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Sierra
  * Firebase SDK version: 5.5.1
  * Library version: N/A
  * Firebase Product: admin

### [REQUIRED] Step 3: Describe the problem

We need the ability to link a new provider to a user via the Admin SDK, this is currently not exposed.

#### Relevant Code:
```javascript 
const credential = firebase.auth[provider].credential(accessToken);

  return firebase
    .auth()
    .currentUser
    .link(credential)
    .then(user => head(user.providerData));
```

**Comment by bojeil-google** [comment]
The APIs you are proposing are client APIs. There is no concept of `currentUser` in the admin SDK.

If you wish to run this from the admin SDK, you can use the client node.js SDK.

**Comment by blackxored** [comment]
The problem is, apologies if it’s something that’s obvious but I just can’t
find it, it’s that the client SDK wouldn’t allow me to sign in with a token
that’s been generated on another client (i.e by a mobile app that passes
this token to my server).

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by hiranya911** [comment]
Closing this since the developer hasn't followed up. It's better to use Stackoverflow for this type of queries.

**Comment by LilJaaY** [comment]
This feature would be useful to me.

What I'm trying to achieve: Phone number verification (NOT phone number authentication. I use a custom auth system)

My idea is to sign the user in with his phone number for the first time (to verify he has access to his phone number). Then, on the server side, link his account with my custom auth system. And finally, 
unlink the phone authentication.
I don't want to do the link/unlink on the client side because it could be bypassed by an attacker.
