### ISSUE TITLE
[Firestore] firestore.Timestamp not available after update to v 11.0.0

### ISSUE THREAD

**Issue by dastrouvy** [firebase/firebase-admin-node#1803]
* Operating System version: Windows 10
  * Firebase SDK version: firebase-admin v11.0.0
  * Firebase Product: Firestore
  * Node.js version: 16

After update of firebase-admin getting runtime error "cannot read property 'now' of undefined".

#### Steps to reproduce:

import {firestore} from 'firebase-admin';

const timestamp = firestore.Timestamp.now();

If downgrade to 10.3.0 it's working OK. (but there is no WithFieldValue support, so that's no workaround )

**Comment by lahirumaramba** [comment]
I think you need to import `Timestamp` type as: `import { Timestamp } from 'firebase-admin/firestore'`
Please see #1793

**Comment by dastrouvy** [comment]
Thank you. It's correct.
Why such big BC changes are not listed somewhere? 
I've been searching in changelogs, but with no result.

**Comment by wolfbane** [comment]
@lahirumaramba  Same issue here after upgrading to 11.0.0 however unable to change to the suggested new syntax because my codebase isn't using module syntax: 

`Error: Failed to load function definition from source: Failed to generate manifest from function source: SyntaxError: Cannot use import statement outside a module`

**Comment by loolooii** [comment]
@lahirumaramba I'm using `firebase-admin` version `11.1.0` and there's no `firebase-admin/firestore`, only `firebase-admin/lib`. Why is this so confusing?

**Comment by jorgsiegel** [comment]
It would have been nice to be informed about this change.
