### ISSUE TITLE
[Firestore] Unhandled error Error read ECONNRESET after enabling 'preferRest'

### ISSUE THREAD

**Issue by johnnyoshika** [firebase/firebase-admin-node#2243]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: firebase-admin@11.9.0
  * Firebase Product: Firestore
  * Node.js version: 16
  * NPM version: 8.1.2

#### Steps to reproduce:

Ever since I enabled `preferRest`:

```
const db = initializeFirestore(app, {
  preferRest: true,
});
```

...I've been getting many `Unhandled error Error
read ECONNRESET` error notifications from Google Cloud. Here's a typical notification message:

![image](https://github.com/firebase/firebase-admin-node/assets/504505/826ec7b2-bf31-4bf6-9ef7-f19eb0ba7ae8)

#### Relevant Code:

```
const db = initializeFirestore(app, {
  preferRest: true,
});
```

**Comment by johnnyoshika** [comment]
Here's another one with a different error message, but also only started appearing after enabling `preferRest`:

![image](https://github.com/firebase/firebase-admin-node/assets/504505/49df3658-f70e-4763-a8f1-ddb08a3f09dc)

**Comment by ehsannas** [comment]
tracking internally b/291972583

**Comment by ehsannas** [comment]
A common root cause of this error is that not all promises are awaited. In other words, there are background tasks that finish _after_ the function loses CPU/Network access. See the "[Do not start background activities](https://cloud.google.com/functions/docs/bestpractices/tips#do_not_start_background_activities)" section.

If there's a more specific repro that you'd like me to investigate, please let me know.

**Comment by johnnyoshika** [comment]
I enabled preferRest in my projects again. I'm not getting the `ECONNRESET` error anymore but the cold start doesn't seem to be any better than before preferRest was enabled.
