### ISSUE TITLE
[FR] Sharable code firebase-admin and firebase between client and server

### ISSUE THREAD

**Issue by ButuzGOL** [firebase/firebase-admin-node#2299]
In version before 9
i had 
getDB().collection('productCategories') etc
getDB() i got from firebase-admin or from firebase 
at i was able to share code

now i switched to 9+
collection(getDB(), 'productCategories') but its not working with firebase-admin
which makes code sharable impossible or i missing something
?

**Comment by hsubox76** [comment]
The Firebase Web SDK (or client JS SDK) and Firebase Admin Node SDK are two different libraries meant for different use cases. The Firebase Admin SDK is not just a Node version of the web SDK. It's meant to be used in a secure server context. Because of that, it makes sense for us not to make the APIs identical.

I'm not sure what your use case is, but if you're using SSR, you can actually use the Firebase JS SDK in both client-rendered and server-rendered code, and don't need to use firebase-admin.

If it's some other use case and you really want to use the namespaced version of the JS/Web SDK (the one where every method begins with `firebase.`) you can use the compat bundles: https://firebase.google.com/docs/web/modular-upgrade

You simply import from those compat paths instead, and you can continue using the same API that existed before v9. We can't guarantee support for that will last forever but it isn't going away in the near future.

**Comment by Kazuyuki-Kazzi-Arai** [comment]
I had the exact same problem. 

The explanation is a great help, but I cannot avoid thinking that the argument for breaking the previous behaviour is purely  technical. From a developer point of view, the underlying technical requirements are not important. What is important though is the consistency of features and code and the ability to use the same code in both back and front end without the need to go against the progress of the API. For me, this has been one of the key benefits of using the Firebase JavaScript API. 

I therefore suggest that it makes more sense for us developers to make the APIs identical (modular).
This must surely have been at least considered when the Firebase Web SDK changes were discussed?

**Comment by rmbusch** [comment]
I am commenting to echo @Kazuyuki-Kazzi-Arai and to say that I cannot emphasize enough how "firebase/admin is meant for the server, firebase is meant for the client" is NOT an excuse to make a giant syntactical overhaul on one (that breaks compat) and not the other.

I have types mirroring my firebase document types my application uses. This ensures code operations read and mutate data within prescribed boundaries and we don't introduce unexpected shaping into our data.  One of the fields a document can have is a DocumentReference, which of course retrieves a DocumentSnapshot. It can also retrieve subcollections, further retrieve DocumentReferences in the subcollection, etc.  The way you do this in the two syntaxes is fundamentally different.  

I am trying to use my types in my cloud functions and now I cannot without writing an entire compatibility/translation layer.  Of course, now I have confirmed that is what I have to do, and I will do it.  But I want to add my voice to the feedback saying this:

If you make major syntax changes across major libraries, you should make the same syntax changes in your other libraries that will share code.
