### ISSUE TITLE
Vulnerability in jose subdependency

### ISSUE THREAD

**Issue by m-wagner98** [firebase/firebase-admin-node#2494]
Environment:
  * Operating System version: _____
  * Firebase SDK version: 12.0.0
  * Firebase Product:Top-level idk (auth, database, storage, etc)
  * Node.js version: n/a
  * NPM version: n/a

#### Steps to reproduce:

1. Create a npm project and install the firebase-admin package.
2. Perform an security analysis of the dependencies using OWASP dependency-check plugin
3. The analysis fails due to a known vulnerability in the jose package.
4. With `npm ls jose` we can find out where the dependency comes from:

<user>@computer% npm ls jose
@app/source@0.0.0 /Users/wagnem46/dev/notificationmanager-v2
└─┬ firebase-admin@12.0.0
  └─┬ jwks-rsa@3.1.0
    └── jose@4.15.4

Vulnerability: https://github.com/panva/jose/security/advisories/GHSA-hhhv-q57g-882q
https://nvd.nist.gov/vuln/detail/CVE-2024-28176

**Comment by lahirumaramba** [comment]
Thanks for filing this issue. Since the vulnerability is in a dependency of `jwks-rsa` the fix should be addressed there. It also doesn't look like `jwks-rsa` pins to a specific version of `jose` so you might be able to upgrade `jose` to `v4.15.5` (which includes the fix) in your environment. See https://github.com/auth0/node-jwks-rsa/issues/403

**Comment by m-wagner98** [comment]
Okay we will upgrade on our environment.
