### ISSUE TITLE
FR: An API or Method to find or select orphaned sub-collections

### ISSUE THREAD

**Issue by evertonrobertoauler** [firebase/firebase-admin-node#355]
Firebase Product: Firestore

Describe the problem:

I couldn't find anywhere a way to select or find orphaned sub-collections, this is possible just manually using the web console.

**Comment by schmidt-sebastian** [comment]
This is in the works and we will update you as we get closer to releasing this.

**Comment by jimmykane** [comment]
Any update  ?

**Comment by schmidt-sebastian** [comment]
`@google-cloud/firestore` v0.18.0 and above support traversing the full set of data in a Firestore database via `DocumentReference.listCollections()` and `CollectionReference.listDocuments()`. You should be able to get the newest version of this SDK if you update your dependency on `firebase-admin`.

**Comment by jimmykane** [comment]
@schmidt-sebastian  how does this work since we don't have the ref?

**Comment by mikelehen** [comment]
@jimmykane I'm not sure what "ref" you are referring to.  Can you elaborate on what you're trying to accomplish?

**Comment by vitriolix** [comment]
This is something I'm curious about as well, if we know we have a bunch of orphaned sub collections from older code that was not properly doing deletes, how can we purge that orphan data?  We won't know the ref or path to those orphaned collections as they used to be subcollections of previously deleted documents

**Comment by schmidt-sebastian** [comment]
With `listDocuments()` and `listCollections()` you should be able to traverse and find any document in your Firestore hierarchy. Note that you might have to traverse your project's data from the root if you don't know where your orphaned documents are located.

**Comment by vitriolix** [comment]
is there a property we can check on a document to see if it's orphaned?

**Comment by schmidt-sebastian** [comment]
Since a document can be considered "orphaned" only when one of its parent documents does not exist, a way to do this would be to walk up the document hierarchy (via `.parent`) and call `get()` on every DocumentReference. You can then use `DocumentSnapshot.exists` to check whether there is a backing document in Firestore.

**Comment by vitriolix** [comment]
great suggestion, works for me 👍

**Comment by svenjacobs** [comment]
Given the information provided in the previous comments I fail to understand how to find orphaned documents of a deleted root collection?

Let's say I once had a root collection `test` with various sub-collections and documents. Let's assume I deleted this collection and did **not** use recursive delete. How can I still find these documents since [Firestore.listCollections()](https://googleapis.dev/nodejs/firestore/latest/Firestore.html#listCollections) will only return existing collections? Without a `CollectionReference` to begin with I cannot use `listDocuments()`.

**Comment by svenjacobs** [comment]
Sorry for mentioning you directly @schmidt-sebastian but could you help me please? 🙏🏼

**Comment by milaGGL** [comment]
Hi @svenjacobs, based on the description, I created a "test" root collection with docs and sub-collection. 
1. when a root collection is deleted via console, I believe it recursively deletes all the data under it, so there should be no orphaned data left.
2. After a root collection with sub-collections is deleted via CLI using "--shallow" option, the `Firestore.listCollections()` did return me the root collection I just deleted, not only the existing collections. And I am able to see the root collection in the firebase console as well. 

Not sure if I missed any steps while reproducing, please let me know if you were not able to get the deleted collections via  `Firestore.listCollections()`.

**Comment by svenjacobs** [comment]
Thank you @milaGGL, that helps! 👍🏼

**Comment by davidoort** [comment]
Hey! Kinda related to this discussion, I'm trying to find all subcollections by sampling documents from the top level collections and then calling `listCollections()` on those refs.

The issue is that to sample some documents of the top level collections I have the requirement of only fetching document references, which I believe I can do with `listDocuments()` - however, I don't see any way of putting limits on this query, whereas this api does seem to make that possible: https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/listDocuments am I missing something? @milaGGL @schmidt-sebastian
