### ISSUE TITLE
FR: Provide externs file to support Google Closure Compiler

### ISSUE THREAD

**Issue by gramic** [firebase/firebase-admin-node#359]
I see that you provided such support for [firebaseui-web](https://github.com/firebase/firebaseui-web/issues/395) project.
It would be very good if you do the same for this project.

**Comment by hiranya911** [comment]
We currently maintain some externs in private for generating jsdocs (https://firebase.google.com/docs/reference/admin/node/admin). But we are moving towards getting rid of them, and just generating documentation straight from the TypeScript files using tsdoc. Maintaining a separate set of externs has always been a challenge due to the extra work involved. Therefore we cannot consider this request at this point.
