### ISSUE TITLE
The caller does not have permission error after upgrading from v6.0 to v6.4

### ISSUE THREAD

**Issue by AndreevskiAleksandar** [firebase/firebase-admin-node#425]
* Operating System version: macOS High Sierra 10.13.3
  * Firebase SDK version: 6.4.0
  * Library version: 6.4.0
  * Firebase Product: admin

I have updated the version on the firebase admin from 6.0.0 to 6.4.0 (clean npm install) and I have started getting this error `The caller does not have permission`. I thought maybe the key was wrong, so I generated a new private key on the Firebase Console, changed the old key with the new one and the issue still persists. Bellow is a pastebin link with the package-lock.json with all of the dependencies.
https://pastebin.com/1VKzydAq

Initialization code:
```
var serviceAccount = require('./../config/keys/serviceAccountKey.json');

admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: env.GCLOUD_DB_URL
});
```

**Comment by AndreevskiAleksandar** [comment]
I have opened a new Firebase Project and now it handles everything just fine. This was a staging server for testing and I am fine with just opening a new one. If the production Firebase acts this way then, that could be a problem for me.
P.S. I have checked all the privileges for the services on both staging (the old faulty) and the production one and they are same from start to end.

**Comment by hiranya911** [comment]
@AndreevskiAleksandar this doesn't look like an issue that can be debugged or fixed at the SDK level--especially since it is happening in one specific project, and the permission errors almost always originate at the Firebase back-end. Please open a [support request](https://firebase.google.com/support/troubleshooter/) so this can be debugged from the back-end. Be sure to specify:

1. The Firebase project ID where the problem occurred.
2. A more complete code sample indicating the services you were calling (Auth, RTDB, FCM etc). From the above description it is not clear which service returned the error.
3. A complete stacktrace from the SDK, if available.

If the problem occurred while accessing RTDB, I would also like to ask you to check the value of the `GCLOUD_DB_URL` environment variable, and that was indeed pointing to the correct database.
