### ISSUE TITLE
database.Reference.push() has no catch but has an Error in it's onComplete handler

### ISSUE THREAD

**Issue by dimitarnestorov** [firebase/firebase-admin-node#433]
### Describe your environment

  * Operating System version: macOS 10.14.2
  * Firebase SDK version: N/A
  * Library version: 6.0.0
  * Firebase Product: database

### Describe the problem
`firebase-admin/lib/index.d.ts`:
![image](https://user-images.githubusercontent.com/8790386/50610290-243b3f00-0edb-11e9-976b-c81de37abd98.png)

I don't even know how is this possible, here's what `@firebase/database/src/api/Reference.d.ts` looks like (Reference has a catch):
![image](https://user-images.githubusercontent.com/8790386/50610555-12a66700-0edc-11e9-8cb4-4ab43c2c5822.png)

**Comment by hiranya911** [comment]
Can you be a bit more specific as to what the problem is? Here's how the JS SDK declares the `push()` method:

`push(value?: any, onComplete?: (a: Error | null) => any): ThenableReference;`

https://github.com/firebase/firebase-js-sdk/blob/c6357fbaf99e80257816dafb28e748de4a039edf/packages/database-types/index.d.ts#L101

As you can see it is identical to how the `push()` method is declared in `firebase-admin`.

**Comment by dimitarnestorov** [comment]
I want to use `.catch` for `.push` but `ThenableReference` doesn't have it. Yet the real `.push` has it. Now I have to use the onComplete handler or use `as Promise<Reference>`.

**Comment by hiranya911** [comment]
This is probably because `ThenableReference` extends from `PromiseLike` instead of `Promise`. It's up to the RTDB team to revise/update this API, so please report it at https://github.com/firebase/firebase-js-sdk. If they agree to make the change, we will update the corresponding typings at our end.

In the meantime you can always do the following to register an error callback with `push()`:

```
      ref.push({foo: 'bar'}, (err) => {
        console.log(err);
      });
```
