### ISSUE TITLE
Feature Request: Listen to Authentication event.

### ISSUE THREAD

**Issue by aqualaguna** [firebase/firebase-admin-node#486]
look here i want to add additional data to firebase authentication.
but firebase only can store `DisplayName`, `email`, `PhotoUrl`, and `uid`.
obviously this not enough meta data to user.
i want to add other data like `gender` or `day of birth`.

the solution :   when user register user must be register also in firestore server for additional data.

this is the quirk: i don't want 2 step into user registration step. it will create inconsistency between the authentication database and firestore database when `storing to firestore` happen to fail. so i search google functions can do listen to user registration event.
but i create a seperate nodejs server and want to listen that event. unfortunately even i can't do that. there is no syntax like `admin.auth().onCreate()`. 
this problem force me using google functions. i don't want to create several backend source code(first for google functions, second for my nodejs server).

**Comment by hiranya911** [comment]
This is not something that can be implemented in the SDK. It needs some large-scale infrastructure changes in the backend, so that the onCreate events can be emitted from Firebase Auth. I don't think this is something we are planning to work on. Cloud Functions is our canonical solution to this problem.

@bojeil-google can you confirm and close?

**Comment by bojeil-google** [comment]
@hiranya911  is correct. You will need to either use Cloud Functions to support this, or just build your own solution via some HTTP endpoint or something.
