### ISSUE TITLE
Creating Android apps in projectManagement does not create corresponding OAuth2 client ids in Google Cloud Console.

### ISSUE THREAD

**Issue by muclipse** [firebase/firebase-admin-node#529]
* Operating System version: Ubuntu, MacOS
  * Firebase SDK version: 7.3.0
  * Library version: 7.3.0
  * Firebase Product: Admin SDK Project Management API

## Problem

In Project Management API in the Admin SDK, creating an Android App through [createAndroidApp](https://firebase.google.com/docs/reference/admin/node/admin.projectManagement.ProjectManagement#createAndroidApp) does not create the corresponding OAuth 2.0 client id in Google Cloud platform. 

This behavior is different when I create a new Android app in the Firebase console, where it creates an OAuth 2.0 client id automatically (The client id is named suffixed by '(auto created by Google Service)').

**Comment by nbegley** [comment]
Hi @muclipse, in order to provision an OAuth client for your Android app, we need you to specify a SHA certificate to be used. We don't support doing that during Android app creation in the REST API or Admin SDK, but you can call [addShaCertificate](https://firebase.google.com/docs/reference/admin/node/admin.projectManagement.AndroidApp#addShaCertificate) to do so after app creation. That will result in an OAuth client being provisioned for your app.
