### ISSUE TITLE
WHERE clause not working properly on 8.0

### ISSUE THREAD

**Issue by rodrigoreal** [firebase/firebase-admin-node#545]
I'm not sure what is happening but my where clauses on firestore collections are not working properly on 8.0 version, i upgraded to 8.0 and lot of the queries don't return the correct results, but when i downgraded back to 7.4 it started working again.
I tried to find some breaking changes but i couldn't find anything related to this.
I'm using cloud functions with node 8.

`
 "@google-cloud/firestore": "^2.1.0",
 "@google-cloud/storage": "^2.5.0",
 "firebase-admin": "^8.0.0",
  "firebase-functions": "^2.3.1",
`

**Comment by hiranya911** [comment]
Can you provide more details? Some sample code, and sample results before and after the upgrade would be useful.

**Comment by schmidt-sebastian** [comment]
See https://github.com/googleapis/nodejs-firestore/issues/667

TL/DR: There is an issue with grpc-js 0.4.1, which has since been unpublished from NPM. We are also pushing a Firestore release to downgrade our GRPC dependency to the previous version. While this release is pending, you can either manually install `@grpc/grpc-js` or remove your node modules and install again.
