### ISSUE TITLE
collection.onSnapshot not retrieving all documents [Firestore]

### ISSUE THREAD

**Issue by lucasSzavara** [firebase/firebase-admin-node#642]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Container using node:11.15-alpine
  * Firebase SDK version: 8.2.0
  * Firebase Product: Firestore
  * Node.js version: 11.15
  * NPM version: Npm default version for image node:11.15-alpine

#### Steps to reproduce:

I have a search in my app that get all users and then apply a filter. As I need it to be in real time, I'm using a snapshot to retrieve the documents. My code was working fine for a few days, but in september 6th morning the query.size property was around 1.5% of the real size (I readed using a android SDK and confirmed using the console). As a workaround, I restarted the server and it worked again, but that is not a real solution, since I had to restart the production server.
Until now I could not reproduce it in my test environment

#### Relevant Code:
The query:
```typescript
admin
    .firestore()
    .collection(collectionName)
    .onSnapshot((data) => {
        console.log(data.size); // Was logging 3, but should log ~2500
        // apply filter
    });
```

Dockerfile:
```Dockerfile
FROM node:11.15-alpine

# install deps
ADD package.json /tmp/package.json
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*
RUN cd /tmp && npm install

# Copy deps
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app

# Setup workdir
WORKDIR /opt/app
COPY . /opt/app

# run
EXPOSE 3000
CMD ["npm", "start"] 

```

**EDIT 1**
From my android app I received a "UNAVAILABLE: The service is temporarily unavailable. Please retry with exponential backoff." error around the same time, not sure if it is correlated

**Comment by schmidt-sebastian** [comment]
@lucasSzavara Thanks for filing this report. This does sound a little scary - the Server SDKs should never raise a snapshot before we have received all documents. While the backend sends us documents one at a time, we buffer these changes until the backend tells us that it has delivered a consistent snapshot. 

Since you are not able to reproduce it, I would suggest that you file a support ticket with our backend support team. They will likely be able to look at your logs (once the ticket has been filed). Include a project ID and the time at which you saw the error: https://cloud.google.com/support-hub/

The query handling on Android is very different and we would need to know whether the `SnapshotMetadata.isFromCache()` flag was set or not to be able to say whether this might constitute expected behavior.

**Comment by lucasSzavara** [comment]
@schmidt-sebastian I just created a case at [https://firebase.google.com/support/](https://firebase.google.com/support/) > Database issues > Cloud Firestore > Queries > Queries help > Different problem and selected admin SDK. I'll keep this thread updated. Thanks for the help!

**Comment by hiranya911** [comment]
This is being tracked via our support system.
