### ISSUE TITLE
[Firestore] firestore.Timestamp.now() different in admin/web

### ISSUE THREAD

**Issue by morgs32** [firebase/firebase-admin-node#657]
Let me know if I should report this at [nodejs-firestore](https://github.com/googleapis/nodejs-firestore) GitHub repo

### [REQUIRED] Step 2: Describe your environment
  * Operating System version: Mac OSX
  * Firebase SDK version: 8.6.0
  * Firebase Product: Firestore admin/web
  * Node.js version: 10.15.1
  * NPM version: 6.11.2

### [REQUIRED] Step 3: Describe the problem
Timestamps from admin library are different from timestamps in web library:

```
// admin.firestore.Timestamp.now();
Timestamp {
  "_nanoseconds": 760000000,
  "_seconds": 1569254823,
}
```

```
// firebase.firestore.Timestamp.now();
Timestamp {
  "nanoseconds": 760000000,
  "seconds": 1569254823,
}
```

**Comment by schmidt-sebastian** [comment]
@morgs32 Thanks for filing this issue! While we try to match the APIs and feature set between the Firestore Mobile Web SDK (https://www.npmjs.com/package/@firebase/firestore) and the Firestore Server SDK (https://www.npmjs.com/package/@firebase/firestore), they are inherently different products and don't share any common code or functionality. As such, we currently cannot guarantee that the internal APIs are consistent.

That being said, if there is a use case we are not supporting due to these differences, please do let us know and we can try to address this.

**Comment by morgs32** [comment]
Ok that makes sense. I'm trying to do something special on the server (like checkout) and send the data back to the client via JSON. Then I was going to let the client pretend it got the data from firebase directly. Right now I'm not able to do an update from the client with that JSON, even though I THINK it looks the same. I'm not yet finished setting up an emulator to test exactly which rules seem to be failing. I'll close this for now and report back if I'm certain it's because of these timestamp objects.
In which case it a) wouldn't be the end of the world to refetch the data on the client or b) something more clever. 
Thanks.
