### ISSUE TITLE
createCustomToken doesn't save customClaim 

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-admin-node#771]
When you create a new user and sign him in with createCustomToken with customClaim, and the user later signs out and signs-in again with admin's createCustomToken this time without the optional customClaim param, the customClaim that was previously set is not returned to the client in the second sign-in.

I believe it is a bug that createCustomToken with customClaim doesn't save the customClaim to that account (UID) for the future re-logins. What is the point of setCustomUserClaims if when the user logs in again later, the customClaim isn't set? Why does createCustomToken method requires customClaim param over and over in order to return customClaim to the client when the customClaim has previously been set? Is there a way to createCustomToken to login the user again and again in the client without specifying customClaim so that whatever customClaim that was set previously gets returned?

Could you confirm if this is a bug because this could lead into a security issue?

**Comment by hiranya911** [comment]
This is working as expected. From the [documentation](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html):

> `createCustomToken()`: Creates a new Firebase custom token (JWT) that can be sent back to a client device to use to sign in with the client SDKs' signInWithCustomToken() methods.

> `setCustomUserClaims()`: Sets additional developer claims on an existing user identified by the provided uid, typically used to define user roles and levels of access. These claims should propagate to all devices where the user is already signed in (after token expiration or when token refresh is forced) and the next time the user signs in. If a reserved OIDC claim name is used (sub, iat, iss, etc), an error is thrown. They are set on the authenticated user's ID token JWT.

I think that's pretty self explanatory. `createCustomToken()` does just that -- it creates a new token (JWT) with the specified claims. If a user signs in with the resulting JWT, those claims are added to the ID token issued by Firebase Auth. Beyond that the claims are not saved anywhere, and if the user signs in later with a different custom token containing different claims, only those new claims will be present in the ID token.

If you want to permanently associate some claims with a user account so that they are always added to the ID token, then `setCustomUserClaims()` is what you need.

From a usage point of view, it's rather unusual to create custom tokens with different claims for the same user, unless some other external event caused a change in the user account:

```
T = 0: createCustomToken('alice', {moderator: true})
.
. Passage of time without any changes to the user account
.
T = 2: createCustomToken('alice', {guest: true}) <-- This is strange and possibly wrong
```

Following illustrates a case when it's acceptable to create custom tokens with different claims:

```
T = 0: createCustomToken('alice', {moderator: true})
.
T = 1: Some external event revokes the user's moderator permissions
.
T = 2: createCustomToken('alice', {guest: true}) <-- This is OK
```

This last example also shows why Firebase not saving custom claims set in the token is a good idea. Otherwise the user will end up with `{moderator: true, guest: true}` after the 2nd sign in.
