### ISSUE TITLE
User beforeCreate [FR]

### ISSUE THREAD

**Issue by madhavajay** [firebase/firebase-admin-node#875]
**Is your feature request related to a problem? Please describe.**
Any idea when the User beforeCreate will be available that was mentioned in this Youtube video?
https://www.youtube.com/watch?v=BGCLPiR_0Lg&feature=youtu.be&t=2148

It would be great for disabling signups without having to add so hook which deletes users afterwards as a hacky workaround.

**Describe the solution you'd like**
The ability to disable public signup for a Firebase account. We still want large anonymous public reads but we do not want accounts.

**Describe alternatives you've considered**
We are using a hook which checks if the account exists in another collection before allowing the creation and then deleting it afterwards if it does not.

**Additional context**
Functionality was mentioned in this video:
https://www.youtube.com/watch?v=BGCLPiR_0Lg&feature=youtu.be&t=2148

**Comment by bojeil-google** [comment]
Hey @madhavajay the feature is still in a limited alpha release. We are still testing it.

**Comment by madhavajay** [comment]
@bojeil-google any chance we can get into an early beta for it? 🤗 👍

**Comment by tpotlog** [comment]
Regarding https://github.com/firebase/firebase-admin-node/issues/875#issuecomment-624186765 is there a change since we would like to use firebase but we will not use it if there is no easy way to disable signups and will use other provider like auth0 . 

This feature which is for some reason not implemented like many other auth provider did  is the only thing that prevents me from choosing Firebase authentication.

**Comment by John0x** [comment]
We need this as well to set custom claims before the first token (upon registration) has been issued

**Comment by marcusx2** [comment]
It was teased 17 months ago!! How come it's not available yet?????

**Comment by bojeil-google** [comment]
The wait is finally over. We just launched [blocking functions](https://cloud.google.com/identity-platform/docs/blocking-functions) support to GA. We apologize for the delay and we hope the additional capabilities (including one of my favorite features: [forwarded IdP / OAuth credentials / claims](https://cloud.google.com/identity-platform/docs/blocking-functions#supported_credentials)) that we added since we announced the feature will make up for it.

**Comment by rocketraman** [comment]
![image](https://user-images.githubusercontent.com/53049/102584886-54367980-40d5-11eb-939a-dfd1a6da8544.png)

Hmm, so to use `beforeCreate` we would have to migrate from Firebase auth to Identity Platform?

**Comment by bojeil-google** [comment]
> ![image](https://user-images.githubusercontent.com/53049/102584886-54367980-40d5-11eb-939a-dfd1a6da8544.png)
> 
> Hmm, so to use `beforeCreate` we would have to migrate from Firebase auth to Identity Platform?

Hey @rocketraman you would need to upgrade to Identity Platform to access this feature. The differences between both services are documented [here](https://cloud.google.com/identity-platform/docs/product-comparison).

**Comment by rocketraman** [comment]
> > ![image](https://user-images.githubusercontent.com/53049/102584886-54367980-40d5-11eb-939a-dfd1a6da8544.png)
> > Hmm, so to use `beforeCreate` we would have to migrate from Firebase auth to Identity Platform?
> 
> Hey @rocketraman you would need to upgrade to Identity Platform to access this feature. The differences between both services are documented [here](https://cloud.google.com/identity-platform/docs/product-comparison).

Hmm, this is quite confusing / non-specific:

> Identity Platform and Firebase Authentication both support a collection of Client and Admin SDKs. To preserve backwards-compatibility, the SDKs occasionally use Firebase branding and naming conventions.

What exactly does "occasionally" mean? How do I know if my existing Firebase SDKs will work with identity platform or not? Since I don't see any reference to SDKs on the identity platform documentation, I'm assuming the statement above means my existing Firebase auth SDKs (and Firebase Auth UI) will work transparently with Identity Platform?

**Comment by bojeil-google** [comment]
Hey @rocketraman, your existing Firebase auth SDKs (and Firebase Auth UI) will work transparently with Identity Platform. Identity Platform is basically Firebase Auth + additional advanced enterprise features + SLAs. They share the same SDKs. Upgrading will not result in any disruption of service. You just upgrade by visiting Identity Platform in the Cloud Console. You will be asked to upgrade there. After upgrading you will get access to additional features (SAML, OIDC, MFA, multi-tenancy, etc) also available in the same Firebase SDKs, though some new features are not shipped in the same SDKs (eg. blocking functions). Only be aware that the service uses a different [pricing](https://cloud.google.com/identity-platform/pricing) model. If you have further questions please reach out to support.

**Comment by John0x** [comment]
> Hey @rocketraman, your existing Firebase auth SDKs (and Firebase Auth UI) will work transparently with Identity Platform. Identity Platform is basically Firebase Auth + additional advanced enterprise features + SLAs. They share the same SDKs. Upgrading will not result in any disruption of service. You just upgrade by visiting Identity Platform in the Cloud Console. You will be asked to upgrade there. After upgrading you will get access to additional features (SAML, OIDC, MFA, multi-tenancy, etc) also available in the same Firebase SDKs, though some new features are not shipped in the same SDKs (eg. blocking functions). Only be aware that the service uses a different [pricing](https://cloud.google.com/identity-platform/pricing) model. If you have further questions please reach out to support.

That isn't a solution to this issue tho then, right? Cause this is for Firebase, not Identity Platform.
I honestly don't think that a beforeCreate hook is reason enough to switch to Identity Platform. Will there be support for the beforeCreate hook for Firebase at some point?
