### ISSUE TITLE
Where is the doc for cloud messaging service?

### ISSUE THREAD

**Issue by sujeet-agrahari** [firebase/firebase-admin-node#891]
I am wandering here since 2 hours. How can you people be so bad at maintaining a proper doc.

Your link takes me here  https://firebase.google.com/docs/cloud-messaging/server

Another link this https://firebase.google.com/docs/reference/admin/node/admin.messaging

All I want to send notifications from a node server. I am unable find a proper doc. 

https://firebase.google.com/docs/reference/admin/node/TopicMessage

Why android is mentioned on this page?

**Comment by hiranya911** [comment]
Please spend some time reading and following the content, instead of skimming over it. The page you've linked above has an entire section covering the Admin SDKs:

> Firebase Admin SDK for FCM
>
> The Admin FCM API handles authenticating with the backend and facilitates sending messages and managing topic subscriptions....
>
> To set up the Firebase Admin SDK, see Add the Firebase Admin SDK to Your Server. If you already have a Firebase project, start with Add the SDK. Then, once the Firebase Admin SDK is installed, you can start writing logic to [build send requests](https://firebase.google.com/docs/cloud-messaging/send-message).

Note that there are many different ways to send FCM notifications, and the page you've linked to is the common landing page (getting started page) for FCM. It has links to other pages that go into more details about each different approach for sending notifications.

**Comment by hiranya911** [comment]
> https://firebase.google.com/docs/reference/admin/node/TopicMessage
> Why android is mentioned on this page?

`android` is a valid property in the FCM notification payload (alongside `apns`, `webpush` and others). So it is listed as it should be.
