### ISSUE TITLE
[FR] Ability to query for documents that do or do not contain a field

### ISSUE THREAD

**Issue by psilospore** [firebase/firebase-admin-node#895]
**Is your feature request related to a problem? Please describe.**

Not sure if this is the right repo. I can close this and move it if needed.
I need to be able to query for documents that do or do not contain a field. That is going to be a common need for us. I was expecting that something like this may work. `await firestore.collection('collection').where("b", "==", null)`

There were two suggested solutions I got in response to slack but they would be suboptimal:
1) query all docs filter in code
2) maintain some exists property or existing fields property

For comparison mongodb has exists: https://docs.mongodb.com/manual/reference/operator/query/exists/

**Describe the solution you'd like**
1) `await firestore.collection('collection').where("b", "==", null)`
2) `await firestore.collection('collection').where("b", "exists", false)`

**Comment by hiranya911** [comment]
Please report Firestore issues/feature requests at the Firestore repo: https://github.com/googleapis/nodejs-firestore

**Comment by schmidt-sebastian** [comment]
Since all of our queries are served by indices, we cannot answer the question on whether a document doe not contain a field. We can, however, provide an answer to the opposite question. You can filter documents by field existence as such:

```
query.orderBy('foo');
```

This will only return documents that have a value set for field 'foo' (but please note that `null` is a value in this context).

Note that you can also file backend feature requests here: https://issuetracker.google.com/savedsearches/5337669
