### ISSUE TITLE
[Firestore] API Feedback – Empty Object Merge Behavior

### ISSUE THREAD

**Issue by amiller-gh** [firebase/firebase-admin-node#987]
### Environment

  * Operating System version: macOS Catalina 10.15.2
  * Firebase SDK version: 7.17.2
  * Firebase Product: Firestore
  * Node.js version: 12.14.1
  * NPM version: 6.14.7

### Problem

It's been discussed in more than a few other places, but the current behavior of `firestore.set('any/document'. { property: {} }, { merge: true })` is unintuitive and dangerous!

ref: https://github.com/firebase/firebase-js-sdk/issues/1371#issuecomment-445066500
ref:  https://github.com/firebase/firebase-admin-node/issues/365
ref: https://github.com/mesqueeb/vuex-easy-firestore/issues/73
ref: https://github.com/firebase/firebase-js-sdk/issues/1371
ref: https://github.com/firebase/firebase-js-sdk/issues/1168

We nearly had a production error because of this database API quirk – we caught it through sheer luck. I wanted to flag it again and make the case for changing the behavior in a future major release.

## The Good
```javascript
firestore.set('any/document'. { property: { foo: 'bar' } }, { merge: true });
firestore.set('any/document'. { property: { biz: 'baz' } }, { merge: true });
console.log(await firestore.doc('any/document').get()).data());
// Expected Log: { foo: 'bar', biz: 'baz' }  👍 
// Actual Log: { foo: 'bar', biz: 'baz' }    😎 
```
## The Bad
```javascript
firestore.set('any/document'. { property: { foo: 'bar' } }, { merge: true });
firestore.set('any/document'. { property: {} }, { merge: true });
console.log(await firestore.doc('any/document').get()).data());
// Expected Log: { foo: 'bar' } 👍 
// Actual Log: { } 😱 
```

This is a very easy mistake to make, especially since it it not clearly called out in the docs, and depending on the setup a system may remove keys to patch update based on user input. This behavior forces extra (expensive!) input validation on deep objects that should not be necessary.

I would expect that **any** destructive operations with `{ merge: true }` must be explicitly set using `FieldValue.delete()`.

**Comment by schmidt-sebastian** [comment]
@amiller-gh Thanks for filing this. We have had some lengthy discussions on how to best implement this. While we know that the current "drop on empty" can be surprising, we found it less surprising that simply ignoring empty objects. Since changing the behavior here would be a major breaking change, I don't think this is realistically going to happen.

We can certainly improve our documentation here. I will use this issue to do so.

**Comment by Zloka** [comment]
I would like to add that I also think this is strange, particularly for apps with offline support where writes are combined at a later time.

My use case, from the point of view of an offline device, is essentially "Create an empty placeholder object if it does not already exist. If it exists, do nothing".

Disclaimer: I could change my data schema so that an "empty placeholder object" would be replaced with _no_ object and handle it accordingly when reading data, but that is besides the point that I also think this behavior is rather unintuitive.

**Comment by hiranya911** [comment]
@schmidt-sebastian can this be closed now?

**Comment by schmidt-sebastian** [comment]
We still need to improve the API documentation.

**Comment by JarnoRFB** [comment]
New firebase user chiming in: I came here because I just tripped over this behavior when updating a document with data from another query that could potentially be empty. I think it definitely makes sense to document the behavior more explicitly. However, I would agree with @amiller-gh that is behavior is really not intuitive and I think it is preferable to provide an intuitive API than to document an unintuitive one. 

 I would also like to bring algebraic argument: I think most people (including me) think of merging as a kind of addition operation and expect `{}` to behave as a neutral element. This also makes sense, since merging objects is basically a union of sets, which can be seen as [equivalent to addition]( https://en.wikipedia.org/wiki/Algebra_of_sets#:~:text=The%20union%20and%20intersection%20of%20sets%20may%20be%20seen%20as%20analogous%20to%20the%20addition%20and%20multiplication%20of%20numbers). In the current API `{}` is treated as an [absorbing element](https://en.wikipedia.org/wiki/Absorbing_element) which apparently trips many people of.

**Comment by schmidt-sebastian** [comment]
Documentation improvement coming. 

We won't be able to adjust the behavior as this would be a breaking change across all of our APIs. While I agree that there are some downsides to the current behavior, we decided early on that the downsides are potentially less than just ignoring empty maps.
