### ISSUE TITLE
[Firestore] FirestoreDataConverter types don't match between js & node sdks

### ISSUE THREAD

**Issue by goleary** [firebase/firebase-admin-node#997]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase JS SDK version:    7.18.0
   * Firebase Admin SDK version:   9.1.0
  * Firebase Product: Firestore
  * Node.js version: 10.20.1
  * NPM version: 6.14.4

### [REQUIRED] Step 3: Describe the problem

- Create a firestore converter using the js sdk
- import and try to use the convert in in admin-sdk (node)
- get type errors

### Error
```
src/index.ts:17:22 - error TS2345: Argument of type 'firebase.firestore.FirestoreDataConverter<Post>' is not assignable to parameter of type 'FirebaseFirestore.FirestoreDataConverter<Post>'.
  Types of property 'fromFirestore' are incompatible.
    Type '(snapshot: QueryDocumentSnapshot<DocumentData>, options: SnapshotOptions) => Post' is not assignable to type '(snapshot: QueryDocumentSnapshot<DocumentData>) => Post'.

       .withConverter(postConverter)
```
#### Relevant Code:

Here is a minimal repo with the error: https://github.com/goleary/firebase-testing-repro

definition of the converter (Taken from docs):
```
import * as firebase from "firebase";

class Post {
  constructor(readonly title: string, readonly author: string) {}

  toString(): string {
    return this.title + ", by " + this.author;
  }
}
export const postConverter: firebase.firestore.FirestoreDataConverter<Post> = {
  toFirestore(post: Post): firebase.firestore.DocumentData {
    return { title: post.title, author: post.author };
  },
  fromFirestore(snapshot: firebase.firestore.QueryDocumentSnapshot): Post {
    const data = snapshot.data()!;
    return new Post(data.title, data.author);
  },
};
```

Attempted use of converter:
```
import * as functions from "firebase-functions";
import * as firebase from "firebase-admin";

// Start writing Firebase Functions
// https://firebase.google.com/docs/functions/typescript

import { postConverter } from "./post";

export const helloWorld = functions.https.onRequest(
  async (request, response) => {
    functions.logger.info("Hello logs!", { structuredData: true });
    response.send("Hello from Firebase!");

    const postSnap = await firebase
      .firestore()
      .collection("posts")
      .withConverter(postConverter) // This line result in an error
      .doc()
      .get();
    const post = postSnap.data();
    if (post !== undefined) {
      post.title; // string
      post.toString(); // Should be defined
    }
  }
);
```

**Comment by schmidt-sebastian** [comment]
@thebrianchen Can you take a look at this?

**Comment by thebrianchen** [comment]
@goleary  Thanks for taking the time to file an issue with a repro!

The error you are seeing is because [JS SDK](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter#fromfirestore)'s `FirestoreDataConverter` is not compatible with the [admin-node SDK](https://googleapis.dev/nodejs/firestore/latest/global.html#FirestoreDataConverter)'s `FirestoreDataConverter`. Since the Node SDK does not have the concept of `SnapshotOptions` when calling `get()` on a `QueryDocumentSnapshot`, we do not expose the `SnapshotOptions` argument on the `fromFirestore()` method, which results in the different converter signatures that are throwing the type error you see. To fix your error, you'll have to import `firebase-admin` and access the converter from your `post.ts` 
file.

I'm going to mark this issue as closed since it's WAI, but feel free to comment if you have any other questions!
